####################################
# YoloV5模型权重路径

weight:  "weights/tong.pt"

# 输入图像的尺寸
input_size: 640
# 类别个数
class_num:  1
# 标签名称
class_name: [ 'tong' ]

# class_name: [ 'red', 'blue']

# 阈值设置
threshold:
  iou: 0.2
  confidence: 0.4
# 计算设备
# - cpu
# - 0 <- 使用GPU
device: 'cpu'
